site_name: Git ENSG
site_url: https://iamvdo.github.io/git-ensg/
repo_url: https://github.com/iamvdo/git-ensg/
edit_uri: 'blob/main/docs/'
nav:
    - Git ENSG: index.md
    - Vincent: vincent-deoliveira.md
    - Victor: nom_prenom.md
theme:
    name: readthedocs
extra_css:
    - theme/extra.css
markdown_extensions:
    - admonition
